# generated by datamodel-codegen:
#   filename:  iea43_wra_data_model.schema.json
#   timestamp: 2025-03-12T15:17:53+00:00

from __future__ import annotations

import re
from datetime import date, datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, field_validator


class BaseModelWithHash(BaseModel):
    def __hash__(self):
        hash_tuple = ()
        for value in self.__dict__.values():
            if isinstance(value, BaseModel):
                continue
            elif isinstance(value, set):
                continue
            else:
                hash_tuple += (value,)
        return hash((type(self),) + hash_tuple)


class PlantType(Enum):
    onshore_wind = "onshore_wind"
    offshore_wind = "offshore_wind"
    solar = "solar"
    NoneType_None = None


class MeasurementStationTypeId(Enum):
    mast = "mast"
    lidar = "lidar"
    sodar = "sodar"
    floating_lidar = "floating_lidar"
    wave_buoy = "wave_buoy"
    adcp = "adcp"
    solar = "solar"
    virtual_met_mast = "virtual_met_mast"
    reanalysis = "reanalysis"


class MastGeometryId(Enum):
    lattice_triangle = "lattice_triangle"
    lattice_square_round_edges = "lattice_square_round_edges"
    lattice_square_sharp_edges = "lattice_square_sharp_edges"
    pole = "pole"
    NoneType_None = None


class DeviceVerticalOrientation(Enum):
    upward = "upward"
    downward = "downward"
    NoneType_None = None


class LoggerOemId(Enum):
    NRG_Systems = "NRG Systems"
    Ammonit = "Ammonit"
    Campbell_Scientific = "Campbell Scientific"
    Vaisala = "Vaisala"
    SecondWind = "SecondWind"
    Kintech = "Kintech"
    Wilmers = "Wilmers"
    Unidata = "Unidata"
    WindLogger = "WindLogger"
    Leosphere = "Leosphere"
    ZX_Lidars = "ZX Lidars"
    AXYS_Technologies = "AXYS Technologies"
    AQSystem = "AQSystem"
    Pentaluum = "Pentaluum"
    Nortek = "Nortek"
    Teledyne_RDI = "Teledyne RDI"
    Aanderaa = "Aanderaa"
    Other = "Other"


class Reanalysis(Enum):
    CFSR = "CFSR"
    ERA_Interim = "ERA-Interim"
    ERA5 = "ERA5"
    JRA_55 = "JRA-55"
    MERRA_2 = "MERRA-2"
    NCAR = "NCAR"
    Other = "Other"


class MeasurementUnitsId(Enum):
    m_s = "m/s"
    cm_s = "cm/s"
    mm_s = "mm/s"
    mph = "mph"
    knots = "knots"
    deg = "deg"
    deg_C = "deg_C"  # noqa: N815
    deg_F = "deg_F"  # noqa: N815
    K = "K"
    field_ = "%"
    mbar = "mbar"
    dbar = "dbar"
    hPa = "hPa"  # noqa: N815
    atm = "atm"
    mmHg = "mmHg"  # noqa: N815
    inHg = "inHg"  # noqa: N815
    kg_m_2 = "kg/m^2"
    kg_m_3 = "kg/m^3"
    V = "V"
    mA = "mA"  # noqa: N815
    A = "A"
    ohm = "ohm"
    Hz = "Hz"
    mm = "mm"
    m = "m"
    s = "s"
    W_m_2 = "W/m^2"
    W = "W"
    kW = "kW"  # noqa: N815
    MW = "MW"
    kWh = "kWh"  # noqa: N815
    MWh = "MWh"
    m_s_2 = "m/s^2"
    lux = "lux"
    dB = "dB"  # noqa: N815
    L = "L"
    g_L = "g/L"  # noqa: N815
    g_kg = "g/kg"
    ppt = "ppt"
    psu = "psu"
    S_m = "S/m"
    field__1 = "-"
    NoneType_None = None


class StatisticTypeId(Enum):
    avg = "avg"
    sd = "sd"
    max = "max"
    min = "min"
    count = "count"
    availability = "availability"
    quality = "quality"
    sum = "sum"
    median = "median"
    mode = "mode"
    range = "range"
    gust = "gust"
    ti = "ti"
    ti30sec = "ti30sec"
    text = "text"


class SensorTypeId(Enum):
    anemometer = "anemometer"
    wind_vane = "wind_vane"
    thermometer = "thermometer"
    barometer = "barometer"
    hygrometer = "hygrometer"
    thermohygrometer = "thermohygrometer"
    voltmeter = "voltmeter"
    ammeter = "ammeter"
    pyranometer = "pyranometer"
    pyrheliometer = "pyrheliometer"
    albedometer = "albedometer"
    field_2d_ultrasonic = "2d_ultrasonic"
    field_3d_ultrasonic = "3d_ultrasonic"
    vertical_anemometer = "vertical_anemometer"
    propeller_anemometer = "propeller_anemometer"
    gill_propeller = "gill_propeller"
    rain_gauge = "rain_gauge"
    ice_detection_sensor = "ice_detection_sensor"
    fog_sensor = "fog_sensor"
    gps = "gps"
    illuminance_sensor = "illuminance_sensor"
    compass = "compass"
    solar_compass = "solar_compass"
    inertial_measurement_unit = "inertial_measurement_unit"
    adcp = "adcp"
    altimeter = "altimeter"
    ctd = "ctd"
    pth = "pth"
    lidar = "lidar"
    sodar = "sodar"
    other = "other"
    NoneType_None = None


class CalibrationUncertaintyItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    reference_bin: float | None = Field(
        None,
        description="The reference bin for the calibration.",
        examples=[5.93],
        title="Reference Bin",
    )
    reference_unit: str | None = Field(
        None,
        description="The reference bin and uncertainty units.",
        examples=["m/s"],
        title="Reference Unit",
    )
    combined_uncertainty: float | None = Field(
        None,
        description="The combined uncertainty associated with the deviation between the reference and the test item at "
        "this reference bin.",
        examples=[0.1],
        title="Combined Uncertainty",
    )


class MountingTypeId(Enum):
    side = "side"
    goal_post = "goal_post"
    top = "top"
    NoneType_None = None


class StructureTypeId(Enum):
    lightning_finial = "lightning_finial"
    aviation_light = "aviation_light"
    guy_wires = "guy_wires"
    other = "other"


class DateFrom(RootModel):
    root: datetime = Field(
        ...,
        description="The date from when these properties are active. If these properties follow a change, then this "
        "Date From should equal the previous Date To. The format of this date should follow ISO 8601 with "
        "the 'T' required. If a timezone is used, it is essential that this timezone is the same as the "
        "logger timezone.",
        examples=["2020-07-28T20:00:00"],
        title="Date From",
    )


class DateTo(RootModel):
    root: datetime | None = Field(
        ...,
        description="The final end date for when these properties are active. If these properties are currently "
        "active please use null. If null is not allowed please use 2100-01-01T00:00:00. The format of "
        "this date should follow ISO 8601 with the 'T' required. If a timezone is used, it is essential "
        "that this timezone is the same as the logger timezone.",
        examples=["2020-07-28T20:00:00", "2100-01-01T00:00:00"],
        title="Date To",
    )


class Notes(RootModel):
    root: str | None = Field(
        ...,
        description="Notes relating to these properties.",
        examples=["I can write anything I want here."],
        title="Notes",
    )


class UpdateAt(RootModel):
    root: datetime | None = Field(
        ...,
        description="The date these properties were last updated.",
        examples=["2020-07-28T20:49:13"],
        title="Date of Update",
    )


class OffsetFromUtcHrs(RootModel):
    root: float | None = Field(
        ...,
        description="The number of hours that the resulting timeseries dataset is offset from UTC. E.g. -5 for "
        "Eastern Standard Time.",
        examples=[
            "-5 (for Eastern Standard Time)",
            "1 (for Central European Time)",
            "5.5 (for India Standard Time)",
        ],
        title="Offset From UTC [hr]",
    )


class AveragingPeriodMinutes(RootModel):
    root: int | None = Field(
        ...,
        description="The number of minutes the model outputs the timeseries data at. Also known as 'time step' "
        "or 'averaging step'",
        examples=["10", "60"],
        title="Averaging Period [min]",
    )


class TimestampIsEndOfPeriod(RootModel):
    root: bool | None = Field(
        ...,
        description="Does the timestamp represent the end of the averaging period. True is for timestamp to represent "
        "the end of the averaging period and false is for timestamp to represent the start of the "
        "averaging period.",
        examples=[
            "true (for timestamp to represent the end of the averaging period)",
            "false (for timestamp to represent the start of the averaging period)",
        ],
        title="Timestamp at End of Period",
    )


class MeasurementType(Enum):
    wind_speed = "wind_speed"
    wind_direction = "wind_direction"
    air_temperature = "air_temperature"
    water_temperature = "water_temperature"
    temperature = "temperature"
    air_pressure = "air_pressure"
    air_density = "air_density"
    relative_humidity = "relative_humidity"
    voltage = "voltage"
    current = "current"
    resistance = "resistance"
    power = "power"
    energy = "energy"
    vertical_wind_speed = "vertical_wind_speed"
    wind_speed_turbulence = "wind_speed_turbulence"
    precipitation = "precipitation"
    ice_detection = "ice_detection"
    global_horizontal_irradiance = "global_horizontal_irradiance"
    direct_normal_irradiance = "direct_normal_irradiance"
    diffuse_horizontal_irradiance = "diffuse_horizontal_irradiance"
    global_tilted_irradiance = "global_tilted_irradiance"
    global_normal_irradiance = "global_normal_irradiance"
    albedo = "albedo"
    soiling_loss_index = "soiling_loss_index"
    illuminance = "illuminance"
    fog = "fog"
    salinity = "salinity"
    conductivity = "conductivity"
    pressure = "pressure"
    gps_coordinates = "gps_coordinates"
    status = "status"
    flag = "flag"
    counter = "counter"
    availability = "availability"
    quality = "quality"
    carrier_to_noise_ratio = "carrier_to_noise_ratio"
    doppler_spectral_broadening = "doppler_spectral_broadening"
    echo_intensity = "echo_intensity"
    signal_to_noise_ratio = "signal_to_noise_ratio"
    motion_corrected_wind_speed = "motion_corrected_wind_speed"
    motion_corrected_wind_direction = "motion_corrected_wind_direction"
    motion_corrected_vertical_wind_speed = "motion_corrected_vertical_wind_speed"
    wave_height = "wave_height"
    wave_significant_height = "wave_significant_height"
    wave_maximum_height = "wave_maximum_height"
    wave_direction = "wave_direction"
    wave_directional_spread = "wave_directional_spread"
    wave_period = "wave_period"
    wave_peak_period = "wave_peak_period"
    water_speed = "water_speed"
    vertical_water_speed = "vertical_water_speed"
    water_direction = "water_direction"
    orientation = "orientation"
    compass_direction = "compass_direction"
    true_north_offset = "true_north_offset"
    tilt = "tilt"
    tilt_x = "tilt_x"
    tilt_y = "tilt_y"
    tilt_z = "tilt_z"
    u = "u"
    v = "v"
    w = "w"
    elevation = "elevation"
    altitude = "altitude"
    height = "height"
    azimuth = "azimuth"
    water_level = "water_level"
    depth = "depth"
    timestamp = "timestamp"
    obukhov_length = "obukhov_length"
    other = "other"


class OrientationReference(Enum):
    magnetic_north = "magnetic_north"
    true_north = "true_north"
    grid_north = "grid_north"
    NoneType_None = None


class HeightReference(Enum):
    ground_level = "ground_level"
    mean_sea_level = "mean_sea_level"
    sea_level = "sea_level"
    lowest_astronomical_tide = "lowest_astronomical_tide"
    sea_floor = "sea_floor"
    other = "other"
    NoneType_None = None


class MastSectionGeometryItem(BaseModelWithHash):
    model_config = ConfigDict(extra="allow")
    # TODO: add validation for uuid and maybe add constructor to generate uuid
    uuid: str | None = Field(
        None,
        description="The unique id to relate this mast section to the mounting arrangement. A UUID can be generated "
        "here https://www.uuidgenerator.net/",
        examples=["bf078172-bbb6-48fe-ac1f-c6605dffb1b5"],
        title="UUID",
    )
    mast_section_height_mm: float | None = Field(
        None,
        description="Towers come in sections that are connected together to make a complete met mast. This is the "
        "height in mm of this met mast section.",
        examples=[6000],
        title="Mast Section Height [mm]",
    )
    pole_diameter_mm: float | None = Field(
        None,
        description="If a pole mast is used, it's diameter in mm.",
        examples=[203],
        title="Pole Diameter [mm]",
    )
    lattice_face_width_at_bottom_mm: float | None = Field(
        None,
        description="The lattice face width at the bottom of the mast section, as measured from leg centre to leg "
        "centre as outlined in [IEC 61400-12-1 2017 Fig G.5](https://user-images.githubusercontent.com/25622575/160807405-24f8ec74-e93f-4454-b41d-92ea30ffeb15.png).",
        # noqa: E501
        examples=[500],
        title="Lattice Face Width at Bottom [mm]",
    )
    lattice_face_width_at_top_mm: float | None = Field(
        None,
        description="The lattice face width at the top of the mast section, as measured from leg centre to leg centre "
        "as outlined in [IEC 61400-12-1 2017 Fig G.5](https://user-images.githubusercontent.com/25622575/160807405-24f8ec74-e93f-4454-b41d-92ea30ffeb15.png).",
        # noqa: E501
        examples=[500],
        title="Lattice Face Width at Top [mm]",
    )
    lattice_leg_width_mm: float | None = Field(
        None,
        description="The lattice leg diameter for a round leg or width for a square cross section leg.",
        examples=[50],
        title="Lattice Leg Width [mm]",
    )
    lattice_leg_is_round_cross_section: bool | None = Field(
        None,
        description="The lattice leg is a round or square cross section. True is for a round leg cross section and "
        "false is for a square leg cross section.",
        examples=[
            "true (for a round leg cross section)",
            "false (for a square leg cross section)",
        ],
        title="Lattice Leg is Round Cross Section",
    )
    lattice_bracing_member_diameter_mm: float | None = Field(
        None,
        description="THIS FIELD WILL BE DEPRECIATED IN THE NEXT MAJOR RELEASE. The lattice diagonal bracing member "
        "diameter.",
        examples=[12],
        title="Lattice Bracing Member Diameter [mm]",
    )
    lattice_bracing_member_diameter_horizontal_mm: float | None = Field(
        None,
        description="The lattice horizontal bracing member diameter in mm.",
        examples=[12],
        title="Lattice Bracing Member Diameter Horizontal [mm]",
    )
    lattice_bracing_member_diameter_diagonal_mm: float | None = Field(
        None,
        description="The lattice diagonal bracing member diameter in mm.",
        examples=[12],
        title="Lattice Bracing Member Diameter Diagonal [mm]",
    )
    lattice_number_of_diagonal_bracing_members: int | None = Field(
        None,
        description="The number of lattice diagonal bracing members that are contained in one of the repetitive "
        "patterns making up a mast section.",
        examples=[1, 2],
        title="Lattice Number of Bracing Members",
    )
    lattice_bracing_member_length_diagonal_mm: float | None = Field(
        None,
        description="The lattice diagonal bracing member length in mm.",
        examples=[512],
        title="Lattice Bracing Member Length Diagonal [mm]",
    )
    number_of_repetitive_patterns_on_face: int | None = Field(
        None,
        description="The number of repetitive patterns on tower face as in the image. Note that for this case the "
        "pattern in red repeats itself 6 times. "
        "https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/images/number_of_repetitive_patterns_on_face.png.",
        # noqa: E501
        examples=[6],
        title="Number of Repetitive Patterns on Face",
    )
    lattice_bracing_member_height_mm: float | None = Field(
        None,
        description="The height of the lattice diagonal bracing members.",
        examples=[900],
        title="Lattice Bracing Member Height [mm]",
    )
    lattice_has_horizontal_member: bool | None = Field(
        None,
        description="This represents masts that have horizontal braces. True is for towers with horizontal braces and "
        "false is for towers without horizontal braces.",
        examples=[
            "true (for towers with horizontal braces)",
            "false (for towers without horizontal braces)",
        ],
        title="Does the tower have horizontal braces?",
    )
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class MastProperties(BaseModel):
    model_config = ConfigDict(extra="allow")
    mast_geometry_id: MastGeometryId | None = Field(
        None,
        description="The type of mast geometry e.g. lattice with a triangular profile or pole. The IEC specifies two "
        "square lattice towers as having rounded edges for their members or sharp edges.",
        title="Mast Geometry",
    )
    mast_oem: str | None = Field(
        None,
        description="The manufacturer of the met mast.",
        examples=["NRG Systems", "Galetech Energy Services"],
        title="Mast OEM",
    )
    mast_serial_number: str | None = Field(
        None,
        description="The manufacturer's serial number of the mast.",
        examples=["XHD12345", "MM01234"],
        title="Mast Serial Number",
    )
    mast_model: str | None = Field(
        None,
        description="The model of the mast.",
        examples=["80m XHD TallTower", "SLX80m"],
        title="Mast Model",
    )
    mast_height_m: float | None = Field(
        None,
        description="The height of the mast itself, not necessarily the top anemometer height.",
        examples=[81.3],
        title="Mast Height [m]",
    )
    date_from: datetime | None = Field(
        None,
        description="The date from when these properties are active. If these properties follow a change, then this "
        "Date From should equal the previous Date To. The format of this date should follow ISO 8601 with "
        "the 'T' required. If a timezone is used, it is essential that this timezone is the same as the "
        "logger timezone.",
        examples=["2020-07-28T20:00:00"],
        title="Date From",
    )
    date_to: DateTo | None = None
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    mast_section_geometry: set[MastSectionGeometryItem] | None = Field(
        None,
        description="This contains the properties of each mast section. Additional properties can be added e.g. "
        "'material' however this wouldn't be part of the Data Model. If an additional property is for "
        "information purposes please consider using 'notes' instead.",
        title="Mast Section Geometry",
    )


class VerticalProfilerProperty(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    device_datum_plane_height_m: float | None = Field(
        None,
        description="The datum plane height of the remote sensing device where the datum feature is defined here: "
        "http://data.windenergy.dtu.dk/ontologies/view/ontolidar/en/page/DatumFeature . For lidars the "
        "datum feature is usually the window and for sodars it is usually the base of the device. These "
        "datum plane heights are also usually referred to as above ground level however it may be above "
        "sea level or above a platform level.",
        examples=[0.5, 1],
        title="Device Datum Plane Height [m]",
    )
    height_reference_id: HeightReference | None = "ground_level"
    device_orientation_deg: confloat(ge=0.0, le=360.0) | None = Field(
        None,
        description="The orientation that the remote sensing device is installed relative to north.",
        title="Device Orientation [deg]",
    )
    orientation_reference_id: OrientationReference | None = None
    device_vertical_orientation: DeviceVerticalOrientation | None = Field(
        None,
        description="The vertical orientation that the remote sensing device is installed. E.g. an ADCP mounted on "
        "the sea floor has an 'upwards' vertical orientation pointing towards the sea surface whereas an "
        "ADCP mounted underneath a buoy has a 'downward' vertical orientation pointing towards the "
        "sea floor.",
        title="Device Vertical Orientation",
    )
    date_from: datetime | None = Field(
        None,
        description="The date from when these properties are active. If these properties follow a change, then this "
        "Date From should equal the previous Date To. The format of this date should follow ISO 8601 with "
        "the 'T' required. If a timezone is used, it is essential that this timezone is the same as the "
        "logger timezone.",
        examples=["2020-07-28T20:00:00"],
        title="Date From",
    )
    date_to: DateTo | None = None
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class LidarConfigItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    flow_corrections_applied: bool | None = Field(
        None,
        description="Is there any flow corrections applied to the measured data by the lidar unit, e.g. "
        "Flow Complexity Recognition (FCR) for WindCubes?",
        examples=[
            "true (for any flow corrections applied)",
            "false (for no flow corrections applied)",
        ],
        title="Flow Corrections Applied",
    )
    date_from: datetime | None = Field(
        None,
        description="The date from when these properties are active. If these properties follow a change, then this "
        "Date From should equal the previous Date To. The format of this date should follow ISO 8601 with "
        "the 'T' required. If a timezone is used, it is essential that this timezone is the same as the "
        "logger timezone.",
        examples=["2020-07-28T20:00:00"],
        title="Date From",
    )
    date_to: DateTo | None = None
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class LoggerMainConfigItem(BaseModelWithHash):
    model_config = ConfigDict(extra="allow")
    logger_oem_id: LoggerOemId = Field(
        ...,
        description="This is the logger or remote sensing device manufacturer id as defined by the IEA Wind Resource "
        "Assessment Data Model Schema.",
        title="Logger OEM",
    )
    logger_model_name: str | None = Field(
        None,
        description="This is the logger or remote sensing device model name. This is usually stated in the data files "
        "from the logger in either the header or footer.",
        examples=["Symphonie Plus3", "CR1000", "Meteo-40M", "WindCube v2"],
        title="Logger Model Name",
    )
    logger_serial_number: str = Field(
        ...,
        description="The logger or remote sensing device serial number. This is sometimes different from the "
        "logger id.",
        title="Logger Serial Number",
    )
    logger_firmware_version: str | None = Field(
        None,
        description="The logger or remote sensing device's Firmware Version. This is the software version that is run "
        "on the logger at the time of data acquisition. This software can be updated and so can sometimes "
        "impact the results of the outputted data. E.g. NRG SymphoniePro, Firmware Version: 3.2.3. "
        "For loggers/devices that have multiple software programmes to process the outputted data the "
        "versions can be concatenated together.",
        title="Logger Firmware Version",
    )
    logger_id: str | None = Field(
        None,
        description="This is the logger or remote sensing device id. It may be set by the logger programmer and may "
        "be different from the logger serial number.",
        examples=["4321", "D123456", "WLS7-999"],
        title="Logger Id",
    )
    logger_name: str | None = Field(
        None,
        description="The logger (or mast name) name assigned to the logger in the logger programme.",
        examples=["AName_MM1"],
        title="Logger Name",
    )
    date_from: DateFrom
    date_to: DateTo | None
    encryption_pin_or_key: str | None = Field(
        None,
        description="The encryption PIN or key used to encrypt the data.",
        examples=["9876", "KkocDuSCk3v5tw4kRveHGQvuD1kYVVbU"],
        title="Encryption PIN or Key",
    )
    enclosure_lock_details: str | None = Field(
        None,
        description="Details about how to open the logger enclosure box when on site.",
        examples=["Combination lock PIN 54321.", "Physical key has id 54321."],
        title="Enclosure Lock Details",
    )
    data_transfer_details: str | None = Field(
        None,
        description="Details about how the data is transferred from the logger to the recipient.",
        examples=[
            "Logger emails to data@developername.com",
            "Retrieve data via LoggerNet.",
        ],
        title="Data Transfer Details",
    )
    offset_from_utc_hrs: OffsetFromUtcHrs | None = None
    sampling_rate_sec: int | None = Field(
        None,
        description="The number of seconds the logger samples data.",
        examples=["1", "2"],
        title="Sampling Rate [s]",
    )
    averaging_period_minutes: AveragingPeriodMinutes | None = None
    timestamp_is_end_of_period: TimestampIsEndOfPeriod | None = None
    clock_is_auto_synced: bool | None = Field(
        None,
        description="Is the logger clock auto-synced with an internet time server to keep accurate time. True is for "
        "when the logger clock is auto-synced and false is for when the logger clock is not auto-synced.",
        examples=[
            "true (for when the logger clock is auto-synced)",
            "false (for when the logger clock is not auto-synced)",
        ],
        title="Clock is Auto-Synced",
    )
    logger_acquisition_uncertainty: float | None = Field(
        None,
        description="The uncertainty of the logger acquisition system as a percentage. This is also referred to as the "
        "uncertainty of the data acquisition system within IEC 61400-12-1. ",
        examples=["0.1"],
        title="Logger Acquisition Uncertainty [%]",
    )
    uncertainty_k_factor: float | None = Field(
        None,
        description="Uncertainty k factor for Logger Acquisition Uncertainty as provided in logger documentation "
        "specification.",
        examples=["2"],
        title="Uncertainty K Factor",
    )
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    lidar_config: set[LidarConfigItem] | None = Field(
        None,
        description="The lidar specific configuration represents how the lidar's specific settings are configured. "
        "For example, if FCR is turned on.",
        title="Lidar Specific Configuration",
    )


class ModelConfigItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    reanalysis: Reanalysis | None = Field(
        None,
        description="The name of the reanalysis dataset that is the source or the result of this model.",
        title="Reanalysis",
    )
    horizontal_grid_resolution_m: int | None = Field(
        None,
        description="The final horizontal grid resolution, in meters, of the model used to create this dataset. If a "
        "reanalysis dataset, this can be an approximation e.g. '50000' for MERRA-2 as it is about 50 km in "
        "the latitudinal direction.",
        examples=["50000", "300"],
        title="Horizontal Grid Resolution [m]",
    )
    model_used: str | None = Field(
        None,
        description="The typical name of the model used to create this dataset. Further details can be added to the "
        "notes.",
        examples=["ECMWF IFS"],
        title="Model Used",
    )
    date_from: DateFrom
    date_to: DateTo | None = None
    offset_from_utc_hrs: OffsetFromUtcHrs | None = None
    averaging_period_minutes: AveragingPeriodMinutes | None = None
    timestamp_is_end_of_period: TimestampIsEndOfPeriod | None = None
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class ColumnNameItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    column_name: str = Field(
        ...,
        description="The column name in the data file which relates to this sensor configuration.",
        title="Column Name",
    )
    statistic_type_id: StatisticTypeId = Field(
        ...,
        description="The statistic, aggregation function or signal e.g. 'average' or 'maximum' that this column "
        "records.",
        examples=[
            "ti30sec (the 10 minute average of the turbulence intensity calculated every 30 seconds within that "
            "10 minute period.)"
        ],
        title="Statistic Type",
    )
    is_ignored: bool | None = Field(
        False,
        description="If you want to ignore this column name, set to True.",
        title="Is Ignored",
    )
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class LoggerMeasurementConfigItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    slope: float | None = Field(
        None,
        description="The slope programmed into the logger for this measurement. This is typically expected for "
        "anemometers and wind vanes, but not necessarily required for other sensor types.",
        title="Logger Slope",
    )
    offset: float | None = Field(
        None,
        description="The offset programmed into the logger. This is typically expected for anemometers and wind vanes, "
        "but not necessarily required for other sensor types.",
        title="Logger Offset",
    )
    sensitivity: float | None = Field(
        None,
        description="The sensitivity programmed into the logger. Usually used for pyranometers. It is the same as "
        "1/slope with zero for offset.",
        title="Logger Sensitivity",
    )
    measurement_units_id: MeasurementUnitsId | None = Field(
        None,
        description="The measurement units of the values the sensor records.",
        title="Measurement Units",
    )
    height_m: float | None = Field(
        None,
        description="The height in meters at which the sensor is deployed, as programmed into the logger. For remote "
        "sensing devices such as lidars and sodars this is the measurement height programmed into the "
        "device where the measurement height is defined here: http://data.windenergy.dtu.dk/controlled-terminology/IEAWindTask32/parameters.measurement_height",
        # noqa: E501
        title="Logger Height [m]",
    )
    serial_number: str | None = Field(
        None,
        description="The serial number of the sensor programmed into the logger.",
        title="Serial Number",
    )
    connection_channel: str | None = Field(
        None,
        description="The connection channel the sensor is wired into on the logger.",
        title="Connection Channel",
    )
    logger_stated_boom_orientation_deg: confloat(ge=0.0, le=360.0) | None = Field(
        None,
        description="The boom orientation of the horizontal boom the sensor is mounted on as programmed into the "
        "logger.",
        title="Logger Stated Boom Orientation [deg]",
    )
    date_from: DateFrom
    date_to: DateTo | None
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    column_name: set[ColumnNameItem] = Field(
        ...,
        description="The group of column names in the data file which relates to this sensor configuration.",
        title="Column Names",
    )


class CalibrationItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    measurement_type_id: MeasurementType | None = None
    slope: float | None = Field(
        None,
        description="The slope programmed into the logger.",
        title="Calibration Slope",
    )
    offset: float | None = Field(
        None,
        description="The offset programmed into the logger.",
        title="Calibration Offset",
    )
    sensitivity: float | None = Field(
        None,
        description="The sensitivity programmed into the logger.",
        title="Calibration Sensitivity",
    )
    report_file_name: str | None = Field(
        None,
        description="The file name of the calibration report.",
        examples=["A12345_calibration.pdf"],
        title="Report File Name",
    )
    report_link: str | None = Field(
        None,
        description="A link to the calibration report.",
        examples=["https://www.dropbox.com/bw/7dzu7xzb/AAN-BNsa?dl=0"],
        title="Report Link",
    )
    calibration_id: str | None = Field(
        None,
        description="The calibration ID is the unique number that the calibration organisation uses to identify a "
        "particular calibration. It may be referred to as Certificate number or Calibration Mark by some "
        "organisations.",
        examples=["1234567", "CERT1234"],
        title="Calibration ID",
    )
    date_of_calibration: date | None = Field(
        None,
        description="The date the sensor calibration took place.",
        examples=["2019-12-06"],
        title="Date of Calibration",
    )
    revision: str | None = Field(
        None,
        description="This is the revision number or other identifier if the calibration report was revised. "
        "The 'date of calibration' and 'calibration id' may stay the same for an update to the report and "
        "so this revision field allows this report to be uniquely identified.",
        examples=["2.0", "B"],
        title="Calibration Revision",
    )
    calibration_organisation: str | None = Field(
        None,
        description="The organisation who performed the calibration.",
        examples=["Deutsche WindGuard", "Ammonit Wind Tunnel GmbH"],
        title="Calibration Organisation",
    )
    place_of_calibration: str | None = Field(
        None,
        description="The unique place or wind tunnel where the calibration took place. E.g. 'place of calibration' "
        "is usually a field on a calibration certificate. If not, a combination of a unique tunnel id or "
        "serial number and the address would suffice. In the Digital Calibration Certificate project this "
        "field maps to 'wind_tunnel_id'.",
        examples=[
            "Windtunnel 2 of Deutsche WindGuard WindTunnel Services GmbH, Varel",
            "AWT Bargeshagen",
        ],
        title="Place of Calibration",
    )
    uncertainty_k_factor: float | None = Field(
        None,
        description="The uncertainty k factor stated in the calibration report.",
        examples=[2],
        title="Uncertainty K Factor",
    )
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    calibration_uncertainty: set[CalibrationUncertaintyItem] | None = Field(
        None,
        description="The sensor calibration details.",
        title="Calibration Uncertainty",
    )


class SensorItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    oem: str | None = Field(
        None,
        description="The measurement sensor manufacturer.",
        examples=["Vector", "NRG Systems", "Thies"],
        title="Sensor OEM",
    )
    model: str | None = Field(
        None,
        description="The measurement sensor model.",
        examples=["#200P", "First Class Advanced", "A100L2"],
        title="Sensor Model",
    )
    serial_number: str | None = Field(
        None,
        description="The serial number of the sensor installed.",
        title="Serial Number",
    )
    sensor_type_id: SensorTypeId | None = Field(
        None,
        description="The measurement sensor type e.g. anemometer.",
        title="Sensor Type",
    )
    classification: str | None = Field(
        None,
        description="The classification of a particular anemometer for this location. This combines the class index "
        "(number) with the terrain class (A, B, C, D or S) e.g. 1.2A. The format of this is validated by "
        "a regex which has the form of ^[0-9][.][0-9][ABCDS]$ i.e. digit.digit followed by a character.",
        examples=["1.0A", "3.2B", "2.7S", "10.32S"],
        title="Classification",
    )
    instrument_poi_height_mm: float | None = Field(
        None,
        description="This is the physical height dimension, in mm, of the sensor's point of interest, i.e. point of "
        "measurement. This is to aid IEC mounting calculations. It is not the height above ground level at "
        "which it is deployed. For example, if the sensor is an anemometer it is the height from the "
        "bottom of the instrument to the centre of the cups. For a sonic anemometer it is the centre of "
        "the sampling volume. For a horizontal propeller anemometer it is the axis of rotation of the "
        "propellers. For a wind vane it is the top of the vane.",
        examples=[
            "169 mm for a Vector A100 anemometer "
            "(https://www.windspeed.co.uk/ws/index.php?option=displaypage&op=page&Itemid=48#dimensions)."
        ],
        title="Instrument Point of Interest Height [mm]",
    )
    is_heated: bool | None = Field(
        None,
        description="Is the sensor heated to reduce the effect of icing. This is usually relevant for wind speed and "
        "wind vane sensors. True is for when the sensor is heated and false is for when the sensor is "
        "not heated.",
        examples=[
            "true (if the sensor is heated)",
            "false (if the sensor is not heated)",
        ],
        title="Is Heated",
    )
    sensor_body_size_mm: float | None = Field(
        None,
        description="This is the instrument body size in mm. This parameter is used in IEC 61400-12-2 to ensure that "
        "the size of the anemometer body is smaller than the diameter of the tube used to mount the "
        "anemometer.",
        examples=["50"],
        title="Sensor Body Size [mm]",
    )
    date_from: DateFrom
    date_to: DateTo | None
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    calibration: set[CalibrationItem] | None = Field(
        None,
        description="The sensor calibration details. This is typically expected for anemometers, but not necessarily "
        "required for other sensor types.",
        title="Calibration",
    )

    @field_validator("classification")
    def validate_classification(cls, value):  # noqa: N805
        pattern = re.compile(r"^[0-9]\.[0-9][ABCDS]$")
        if value and not pattern.match(value):
            raise ValueError("Invalid classification format")
        return value


class MountingArrangementItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    mast_section_geometry_uuid: str | None = Field(
        None,
        description="The uuid to link this Measurement Point's mounting arrangement to the Mast Section Geometry. "
        "A UUID can be generated here https://www.uuidgenerator.net/",
        title="Mast Section Geometry UUID",
    )
    mounting_type_id: MountingTypeId | None = Field(
        None,
        description="The mounting type the sensor is mounted onto the mast e.g. an anemometer top mounted above the "
        "mast or a pair of anemometers mounted in the goal post configuration.",
        title="Mounting Type",
    )
    boom_orientation_deg: confloat(ge=0.0, le=360.0) | None = Field(
        None,
        description="The boom orientation of the horizontal boom the sensor is mounted on.",
        title="Boom Orientation [deg]",
    )
    vane_dead_band_orientation_deg: confloat(ge=0.0, le=360.0) | None = Field(
        None,
        description="The wind vane dead band orientation.",
        title="Vane Dead Band Orientation [deg]",
    )
    orientation_reference_id: OrientationReference | None = None
    tilt_angle_deg: confloat(ge=-90.0, le=90.0) | None = Field(
        None,
        description="The tilt angle of either the vertical upstand the sensor is mounted on.",
        title="Tilt Angle [deg]",
    )
    boom_oem: str | None = Field(None, description="The boom OEM.", title="Boom OEM")
    boom_model: str | None = Field(None, description="The boom model.", title="Boom Model")
    upstand_height_mm: confloat(ge=0.0) | None = Field(
        None,
        description="The height, measured in millimeters, of the upstand.",
        title="Upstand Height [mm]",
    )
    upstand_diameter_mm: confloat(ge=0.0) | None = Field(
        None,
        description="The diameter, measured in millimeters, of the upstand.",
        title="Upstand Diameter [mm]",
    )
    boom_diameter_mm: confloat(ge=0.0) | None = Field(
        None,
        description="The diameter, measured in millimeters, of the boom.",
        title="Boom Diameter [mm]",
    )
    boom_length_mm: confloat(ge=0.0) | None = Field(
        None,
        description="The length, measured in millimeters, of the boom.",
        title="Boom Length [mm]",
    )
    distance_from_mast_to_sensor_mm: confloat(ge=0.0) | None = Field(
        None,
        description="The distance, measured in millimeters, of edge of the mast to the centre of the sensor.",
        title="Distance Mast to Sensor [mm]",
    )
    date_from: DateFrom
    date_to: DateTo | None
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class InterferenceStructure(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    structure_type_id: StructureTypeId = Field(
        ...,
        description="The type of structure that is causing an interference in the sensor's measurements.",
        title="Structure Type",
    )
    orientation_from_mast_centre_deg: confloat(ge=0.0, le=360.0) | None = Field(
        None,
        description="The orientation of the interference structure, relative to the centre of the mast, causing an "
        "impact on the sensor's measurements.",
        title="Orientation from Mast Centre [deg]",
    )
    orientation_reference_id: OrientationReference | None = None
    distance_from_mast_centre_mm: float | None = Field(
        None,
        description="The distance from the mast centre to the interference structure causing an impact on the sensor's "
        "measurements.",
        examples=[900],
        title="Distance from Mast Centre [mm]",
    )
    diameter_of_interference_structure_mm: float | None = Field(
        None,
        description="The diameter of the Interference Structure. If lightning finial, then it can be used for IEC "
        "validation. For irregularly shaped structures, a representative diameter would be sufficient for "
        "an analyst to understand it's size.",
        examples=[30],
        title="Diameter of Interference Structure [mm]",
    )
    date_from: DateFrom
    date_to: DateTo | None = None
    notes: Notes | None = None
    update_at: UpdateAt | None = None


class MeasurementPointItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    name: str = Field(
        ...,
        description="The name the measurement point is commonly referred to. This is the name that is used to refer to "
        "the data in an analysis and reporting.",
        title="Name",
    )
    measurement_type_id: MeasurementType
    height_m: float | None = Field(
        ...,
        description="The height (in meters) typically above ground level that the measurement is taking place. If you "
        "do not yet know the height please use null.",
        title="Height [m]",
    )
    height_reference_id: HeightReference | None = "ground_level"
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    logger_measurement_config: set[LoggerMeasurementConfigItem] = Field(
        ...,
        description="The measurement configuration that is programmed into the logging device.",
        title="Logger Measurement Configuration",
    )
    sensor: set[SensorItem] | None = Field(
        None,
        description="This represents information about the sensor taking the measurements.",
        title="Sensor",
    )
    mounting_arrangement: set[MountingArrangementItem] | None = Field(
        None,
        description="This describes how the sensor is mounted onto the met mast.",
        title="Mounting Arrangement",
    )
    interference_structures: set[InterferenceStructure] | None = Field(
        None, description="", title="Interference Structures"
    )


class MeasurementLocationItem(BaseModelWithHash):
    model_config = ConfigDict(extra="forbid")
    uuid: str | None = Field(
        None,
        description="The unique identifier of the measurement location in the UUID format. A UUID can be generated "
        "here https://www.uuidgenerator.net/",
        examples=["3d40f012-a525-4024-a626-5fcf954c59cf"],
        title="UUID",
    )
    name: str = Field(
        ...,
        description="The name given to the measurement location i.e. to the met mast or remote sensing device. Unique "
        "names are recommended to avoid two locations in the same context being given the same name.",
        examples=["AName_MM1"],
        title="Name",
    )
    latitude_ddeg: confloat(ge=-90.0, le=90.0) = Field(
        ...,
        description="Latitude coordinate in the Geographic Coordinate System using the WGS84 reference coordinate "
        "system, [EPSG:4326](https://epsg.io/4326). Unit of measure is in decimal degrees. Latitude lines "
        "are parallel to the equator where their position ranges from -90 degrees at the south pole to 90 "
        "degrees at the north pole.",
        examples=[52.973],
        title="Latitude [ddeg]",
    )
    longitude_ddeg: confloat(ge=-180.0, le=180.0) = Field(
        ...,
        description="Longitude coordinate in the Geographic Coordinate System using the WGS84 reference coordinate "
        "system, [EPSG:4326](https://epsg.io/4326). Unit of measure is in decimal degrees. Longitude "
        "lines are perpendicular to the equator where their position ranges from 0 deg at Greenwich Mean "
        "Time increasing to positive 180 deg as you move eastward and decreasing to negative 180 deg as "
        "you move westward.",
        examples=[-9.431],
        title="Longitude [ddeg]",
    )
    measurement_station_type_id: MeasurementStationTypeId = Field(
        ...,
        description="The type of measurement station. This must be one of either met mast, lidar (a vertical profiler),"
        " sodar (also a vertical profiler), floating lidar (floating vertical profiler lidar), wave buoy,"
        " ADCP (Acoustic Doppler Current Profiler) or a solar measurement station.",
        title="Measurement Station Type",
    )
    notes: Notes | None = None
    update_at: UpdateAt | None = None
    mast_properties: MastProperties | None = Field(
        None,
        description="The properties of the installed met mast/tower. Additional properties can be added "
        "e.g. 'material' however this wouldn't be part of the Data Model. If an additional property is for "
        "information purposes please consider using 'notes' instead.",
        title="Mast Properties",
    )
    vertical_profiler_properties: set[VerticalProfilerProperty] | None = Field(
        None,
        description="Vertical profiler remote sensing devices (e.g. lidar, sodar and floating lidar) installation "
        "specific properties.",
        title="Vertical Profiler Properties",
    )
    logger_main_config: set[LoggerMainConfigItem] | None = Field(
        None,
        description="This represents how the logger's main settings are configured. For example, it's sampling rate or "
        "averaging period. For remote sensing devices, such as lidar's, the device itself is considered as "
        "a logger and so these logger configuration attributes should be used to describe the lidar.",
        title="Logger Configuration",
    )
    model_config_: set[ModelConfigItem] | None = Field(
        None,
        alias="model_config",
        description="This represents how a simulation model or other model that produces a synthetic timeseries dataset"
        " is configured. This also includes reanalysis datasets.",
        title="Model Configuration",
    )
    measurement_point: set[MeasurementPointItem] = Field(
        ...,
        description="This represents a point in space where a measurement takes place.",
        title="Measurement Point",
    )


class IeaWindResourceAssessmentDataModel(BaseModel):
    model_config = ConfigDict(extra="allow")
    author: str = Field(
        ...,
        description="The person or system who created this data model representing a specific mast.",
        examples=["Stephen Holleran", "Joe Bloggs"],
        title="Author",
    )
    organisation: str = Field(
        ...,
        description="The organisation the Author is from.",
        examples=["brightwind", "Wind Developer Ltd."],
        title="Organisation",
    )
    date_created: date = Field(
        ...,
        description="The date this file was created. Format should be YYYY-MM-DD",
        examples=["2020-07-28"],
        title="Date",
        alias="date",
    )
    version: str = Field(
        ...,
        description="The version of the IEA WRA Data Model this file is based on. The format of this follows Semantic "
        "Versioning with the year and month tagged on after. E.g. 1.1.1-2020.07",
        examples=["0.1.0-2020.06", "1.1.1-2020.07"],
        title="Version",
    )
    license: str | None = Field(
        None,
        description="Expected to be used as the Dublin Core Metadata Initiative intended. "
        "Link: http://purl.org/dc/terms/license Definition: A legal document giving official permission "
        "to do something with the resource. Comment: Recommended practice is to identify the license "
        "document with a URI. If this is not possible or feasible, a literal value that identifies the "
        "license may be provided.",
        examples=["https://opensource.org/license/bsd-3-clause/", "BSD-3-Clause"],
        title="License",
    )
    plant_name: str | None = Field(
        None,
        description="The name of the wind farm this met mast is associated with.",
        examples=["A Name of Wind Farm"],
        title="Plant Name",
    )
    plant_type: PlantType | None = Field(
        None,
        description="The type of renewable generation plant it is.",
        title="Plant Type",
    )
    measurement_location: set[MeasurementLocationItem] = Field(
        ...,
        description="This is the geographic location of the meteorological measurement station i.e. a met mast/tower "
        "or remote sensing device.",
        title="Measurement Location",
    )

    @field_validator("version")
    def validate_classification(cls, value):  # noqa: N805
        pattern = re.compile(r"^([0-9]{1,2})[.]([0-9]{1,2})[.]([0-9]{1,2})-([0-9]{4})[.]([0-9]{2})$")
        if value and not pattern.match(value):
            raise ValueError("Invalid version format")
        return value
