name: Compile Calibration Cert Documentation to HTML

on:
  push:
    branches:
      - calibration_schema
    paths:
      - 'schema/**'
      - '.github/workflows/compile_cert_docs.yml'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: 'calibration_schema'

#       - name: Copy schema
#         run: cp ./schema/iea43_wra_data_model.schema.json ./app/src/schema.json

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install json-schema-for-humans
        run: pip install json-schema-for-humans

      - name: Clear docs folder
        run: rm -rf digital_calibration_certificate/docs && mkdir -p digital_calibration_certificate/docs

      - name: Compile docs to HTML
        run: generate-schema-doc --expand-buttons digital_calibration_certificate/schema/iea43_digital_calibration_certificate.schema.json digital_calibration_certificate/docs/schema_doc.html

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add digital_calibration_certificate/docs
          git commit -m "Compile documentation"

      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
          branch: 'calibration_schema'
 
