name: Compile Documentation to HTML

on:
  push:
    branches:
      - master
    paths:
      - 'schema/**'
      - '.github/workflows/compile_docs.yml'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Copy schema
        run: cp ./schema/iea43_wra_data_model.schema.json ./app/src/schema.json

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install json-schema-for-humans
        run: pip install json-schema-for-humans

      - name: Clear docs folder
        run: rm -rf docs && mkdir -p docs

      - name: Compile docs to HTML
        run: generate-schema-doc --expand-buttons schema/iea43_wra_data_model.schema.json docs/schema_doc.html

      - name: Apply documentation style overrides
        run: |
          cat .github/doc_assets/schema_doc_overrides.css >> docs/schema_doc.css
          cat .github/doc_assets/schema_doc_type_annotations.js >> docs/schema_doc.min.js

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Compile documentation"

      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs
          keep_files: true
