name: Deploy Form App to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'schema/**'
      - '.github/workflows/deploy_app.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Copy schema
        run: cp ./schema/iea43_wra_data_model.schema.json ./app/src/schema.json
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Clean up JSON schema for use with Form App
        run: python ./app/transform_json_schema.py ./app/src/schema.json
      
      - name: Read schema
        id: vars
        run: echo ::set-output name=schema::$(cat ./app/src/schema.json)
        
      - name: Show schema
        run: echo ${{ steps.vars.outputs.schema }}

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: ./app
      - run: npm run build
        working-directory: ./app

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./app/build
